version: '3.8'
services:
    mongo:
        image: 'mongo:5.0.3'
        container_name: mongodb
        ports:
            - "27017:27017"
        env_file: 
            - ./.env
        environment:
            - MONGO_INITDB_DATABASE=${DATABASE_NAME}
            - MONGO_INITDB_ROOT_USERNAME=${DATABASE_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}